# tarot_data.py
# 78 lá bài Tarot - Tiếng Việt
# Hình ảnh: Rider-Waite deck (Public Domain) từ Wikimedia Commons

BASE_URL = "https://en.wikipedia.org/wiki/Special:FilePath/"

def img(filename):
    return BASE_URL + filename

TAROT_CARDS = [
    # ══════════════════════════════════════════
    # MAJOR ARCANA (22 lá)
    # ══════════════════════════════════════════
    {
        "id": 0,
        "name": "Kẻ Ngốc",
        "english": "The Fool",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_00_Fool.jpg"),
        "keywords_up": ["khởi đầu mới", "tự do", "hồn nhiên", "phiêu lưu"],
        "keywords_rev": ["liều lĩnh", "bất cẩn", "ngây thơ quá mức"],
        "upright": "Một khởi đầu tươi mới đầy hứng khởi đang chờ bạn. Hãy dũng cảm bước vào hành trình mới với trái tim rộng mở, tin tưởng vào vũ trụ và buông bỏ sự sợ hãi.",
        "reversed": "Sự liều lĩnh thiếu suy nghĩ hoặc do dự thái quá đang cản trở bạn. Hãy cân nhắc kỹ lưỡng trước khi hành động, đừng để cảm xúc nhất thời dẫn lối.",
    },
    {
        "id": 1,
        "name": "Pháp Sư",
        "english": "The Magician",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_01_Magician.jpg"),
        "keywords_up": ["ý chí", "khéo léo", "sáng tạo", "tiềm năng"],
        "keywords_rev": ["thao túng", "lãng phí tài năng", "thiếu tự tin"],
        "upright": "Bạn sở hữu đầy đủ công cụ và tài năng để biến ước mơ thành hiện thực. Tập trung ý chí, hành động quyết đoán — mọi thứ đều nằm trong tầm tay bạn.",
        "reversed": "Tài năng đang bị lãng phí hoặc dùng sai mục đích. Cẩn thận với những kẻ lừa đảo quanh bạn, hoặc chính bạn đang tự lừa dối bản thân.",
    },
    {
        "id": 2,
        "name": "Nữ Tư Tế",
        "english": "The High Priestess",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_02_High_Priestess.jpg"),
        "keywords_up": ["trực giác", "bí ẩn", "nội tâm", "tiềm thức"],
        "keywords_rev": ["bí mật che giấu", "thiếu lắng nghe nội tâm"],
        "upright": "Hãy tin vào trực giác của bạn — câu trả lời nằm sâu trong tâm hồn bạn. Dành thời gian tĩnh lặng, lắng nghe tiếng nói bên trong và những điều chưa được nói ra.",
        "reversed": "Bạn đang bỏ qua giọng nói nội tâm quan trọng, hoặc có bí mật nào đó đang ảnh hưởng tiêu cực. Hãy đối mặt với sự thật mà bạn đang né tránh.",
    },
    {
        "id": 3,
        "name": "Hoàng Hậu",
        "english": "The Empress",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_03_Empress.jpg"),
        "keywords_up": ["phong phú", "nuôi dưỡng", "sáng tạo", "thiên nhiên"],
        "keywords_rev": ["phụ thuộc", "thiếu sáng tạo", "bỏ bê bản thân"],
        "upright": "Năng lượng dồi dào và sự phong phú đang bao quanh bạn. Đây là thời điểm để nuôi dưỡng các mối quan hệ, ấp ủ dự án sáng tạo và kết nối với vẻ đẹp của cuộc sống.",
        "reversed": "Bạn đang bỏ bê việc chăm sóc bản thân hoặc người thân. Cần tìm lại sự cân bằng giữa cho đi và nhận lại, giữa công việc và nghỉ ngơi.",
    },
    {
        "id": 4,
        "name": "Hoàng Đế",
        "english": "The Emperor",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_04_Emperor.jpg"),
        "keywords_up": ["quyền uy", "cấu trúc", "kỷ luật", "bảo vệ"],
        "keywords_rev": ["độc đoán", "thiếu linh hoạt", "kiểm soát thái quá"],
        "upright": "Thời điểm để xây dựng nền tảng vững chắc, thiết lập trật tự và kỷ luật. Hãy lãnh đạo bằng sự minh mẫn và trách nhiệm, không phải bằng nỗi sợ hãi.",
        "reversed": "Sự kiểm soát quá mức đang gây tổn hại. Có thể bạn hoặc ai đó đang lạm dụng quyền lực. Hãy học cách buông bỏ và tin tưởng người khác.",
    },
    {
        "id": 5,
        "name": "Giáo Hoàng",
        "english": "The Hierophant",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_05_Hierophant.jpg"),
        "keywords_up": ["truyền thống", "tâm linh", "học hỏi", "hướng dẫn"],
        "keywords_rev": ["phá vỡ quy tắc", "giáo điều", "nổi loạn"],
        "upright": "Tìm kiếm sự hướng dẫn từ người có kinh nghiệm hoặc truyền thống lâu đời. Đây là lúc học hỏi từ những bài học đã được kiểm chứng bởi thời gian.",
        "reversed": "Bạn cảm thấy bị giam cầm bởi các quy tắc cũ kỹ. Đã đến lúc tự đặt câu hỏi về những gì bạn được dạy và tìm ra con đường riêng của mình.",
    },
    {
        "id": 6,
        "name": "Tình Nhân",
        "english": "The Lovers",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_06_Lovers.jpg"),
        "keywords_up": ["tình yêu", "lựa chọn", "hài hòa", "giá trị"],
        "keywords_rev": ["mâu thuẫn nội tâm", "lựa chọn sai lầm", "bất hòa"],
        "upright": "Một sự lựa chọn quan trọng liên quan đến tình yêu hoặc các giá trị cốt lõi. Hãy lắng nghe trái tim và chọn theo đúng bản sắc thật của mình.",
        "reversed": "Xung đột nội tâm hoặc mâu thuẫn trong mối quan hệ. Cần trung thực với bản thân về những gì bạn thực sự muốn và cần.",
    },
    {
        "id": 7,
        "name": "Cỗ Xe",
        "english": "The Chariot",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_07_Chariot.jpg"),
        "keywords_up": ["chiến thắng", "kiểm soát", "quyết tâm", "tiến lên"],
        "keywords_rev": ["mất kiểm soát", "thiếu hướng đi", "bị trì hoãn"],
        "upright": "Chiến thắng đang chờ bạn nếu bạn duy trì sự tập trung và kiên định. Hãy kiểm soát cảm xúc, định rõ mục tiêu và tiến về phía trước với ý chí mạnh mẽ.",
        "reversed": "Bạn đang cảm thấy lạc lõng hoặc mất kiểm soát. Hãy dừng lại, tìm lại phương hướng trước khi tiếp tục hành trình.",
    },
    {
        "id": 8,
        "name": "Sức Mạnh",
        "english": "Strength",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_08_Strength.jpg"),
        "keywords_up": ["dũng cảm", "kiên nhẫn", "lòng trắc ẩn", "nội lực"],
        "keywords_rev": ["nghi ngờ bản thân", "yếu đuối nội tâm", "lo âu"],
        "upright": "Sức mạnh thực sự đến từ sự bình tĩnh và lòng trắc ẩn, không phải từ sức mạnh thô bạo. Bạn có đủ dũng khí để đối mặt với thử thách bằng sự nhẹ nhàng và kiên định.",
        "reversed": "Nỗi sợ hãi và nghi ngờ bản thân đang kéo bạn xuống. Hãy nhớ rằng bạn mạnh mẽ hơn bạn nghĩ — cần tìm lại niềm tin vào chính mình.",
    },
    {
        "id": 9,
        "name": "Ẩn Sĩ",
        "english": "The Hermit",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_09_Hermit.jpg"),
        "keywords_up": ["nội tâm", "cô đơn", "tìm kiếm sự thật", "khôn ngoan"],
        "keywords_rev": ["cô lập", "từ chối giúp đỡ", "lạc lối"],
        "upright": "Đây là thời điểm để rút lui khỏi tiếng ồn bên ngoài và lắng nghe tiếng nói bên trong. Câu trả lời bạn tìm kiếm nằm trong sự tĩnh lặng và chiêm nghiệm.",
        "reversed": "Sự cô lập đang trở thành rào cản. Bạn đang từ chối sự giúp đỡ của người khác hoặc tránh né xã hội một cách không lành mạnh.",
    },
    {
        "id": 10,
        "name": "Bánh Xe Vận Mệnh",
        "english": "Wheel of Fortune",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_10_Wheel_of_Fortune.jpg"),
        "keywords_up": ["thay đổi", "may mắn", "vận mệnh", "chu kỳ"],
        "keywords_rev": ["vận rủi", "kháng cự thay đổi", "phá vỡ chu kỳ"],
        "upright": "Bánh xe đang quay — sự thay đổi lớn đang đến, mang theo may mắn và cơ hội. Hãy sẵn sàng đón nhận những điều tốt đẹp mà số phận mang lại.",
        "reversed": "Giai đoạn vận rủi hoặc bạn đang kháng cự những thay đổi tất yếu. Hãy nhớ: mọi chu kỳ đều có điểm bắt đầu và kết thúc.",
    },
    {
        "id": 11,
        "name": "Công Lý",
        "english": "Justice",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_11_Justice.jpg"),
        "keywords_up": ["công bằng", "sự thật", "nhân quả", "trách nhiệm"],
        "keywords_rev": ["bất công", "né tránh trách nhiệm", "thiên vị"],
        "upright": "Sự thật sẽ được phơi bày và công bằng sẽ được thực thi. Hãy hành động trung thực và chịu trách nhiệm về lựa chọn của mình — nhân quả không bao giờ sai.",
        "reversed": "Sự bất công đang xảy ra hoặc bạn đang né tránh trách nhiệm. Hãy đối mặt với hậu quả của những quyết định đã qua.",
    },
    {
        "id": 12,
        "name": "Người Bị Treo",
        "english": "The Hanged Man",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_12_Hanged_Man.jpg"),
        "keywords_up": ["buông bỏ", "góc nhìn mới", "hy sinh", "tạm dừng"],
        "keywords_rev": ["trì hoãn", "cứng đầu", "hy sinh vô ích"],
        "upright": "Đôi khi cần phải dừng lại và nhìn từ góc độ khác. Sự hy sinh và kiên nhẫn chờ đợi sẽ mang lại những nhận thức sâu sắc bạn cần.",
        "reversed": "Bạn đang trì hoãn không cần thiết hoặc cứng đầu không chịu thay đổi. Đã đến lúc hành động thay vì tiếp tục chờ đợi.",
    },
    {
        "id": 13,
        "name": "Cái Chết",
        "english": "Death",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_13_Death.jpg"),
        "keywords_up": ["chuyển hóa", "kết thúc và bắt đầu", "buông bỏ", "thay đổi"],
        "keywords_rev": ["kháng cự thay đổi", "bị mắc kẹt", "sợ kết thúc"],
        "upright": "Một chương sách cũ đang khép lại để nhường chỗ cho điều mới tươi sáng hơn. Hãy dũng cảm buông bỏ những gì không còn phục vụ bạn nữa.",
        "reversed": "Bạn đang bám víu vào quá khứ hoặc tránh né sự thay đổi tất yếu. Nỗi sợ kết thúc đang ngăn bạn tái sinh.",
    },
    {
        "id": 14,
        "name": "Điều Độ",
        "english": "Temperance",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_14_Temperance.jpg"),
        "keywords_up": ["cân bằng", "kiên nhẫn", "điều hòa", "chữa lành"],
        "keywords_rev": ["mất cân bằng", "thái quá", "thiếu kiên nhẫn"],
        "upright": "Sự cân bằng và hài hòa là chìa khóa lúc này. Hãy kiên nhẫn, pha trộn các yếu tố khác nhau một cách khéo léo và để mọi thứ phát triển từ từ.",
        "reversed": "Bạn đang mất cân bằng nghiêm trọng trong một lĩnh vực nào đó. Hãy nhìn nhận lại và điều chỉnh trước khi mọi thứ vượt khỏi tầm kiểm soát.",
    },
    {
        "id": 15,
        "name": "Ác Quỷ",
        "english": "The Devil",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_15_Devil.jpg"),
        "keywords_up": ["ràng buộc", "vật chất", "cám dỗ", "bóng tối nội tâm"],
        "keywords_rev": ["giải phóng", "phá vỡ xích xiềng", "nhận thức"],
        "upright": "Bạn đang bị trói buộc bởi những thói quen tiêu cực, mối quan hệ độc hại hay ham muốn vật chất. Xích xiềng thực ra không chặt như bạn nghĩ — bạn có sức mạnh để thoát ra.",
        "reversed": "Bạn đang bắt đầu nhận ra và giải phóng bản thân khỏi những ràng buộc. Đây là bước tiến quan trọng hướng đến tự do thực sự.",
    },
    {
        "id": 16,
        "name": "Tòa Tháp",
        "english": "The Tower",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_16_Tower.jpg"),
        "keywords_up": ["sụp đổ bất ngờ", "hỗn loạn", "sự thật phơi bày", "thức tỉnh"],
        "keywords_rev": ["tránh né thảm họa", "sợ thay đổi", "chống lại phá hủy"],
        "upright": "Một cơn bão sắp đến — những nền tảng không vững chắc sẽ sụp đổ. Đau đớn nhưng cần thiết: chỉ khi phá bỏ cái cũ, cái mới tốt đẹp hơn mới được xây dựng.",
        "reversed": "Bạn đang tránh né một sự thay đổi cần thiết và đau đớn. Hoặc bạn đang dần vượt qua giai đoạn hỗn loạn và bắt đầu ổn định trở lại.",
    },
    {
        "id": 17,
        "name": "Ngôi Sao",
        "english": "The Star",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_17_Star.jpg"),
        "keywords_up": ["hy vọng", "cảm hứng", "chữa lành", "niềm tin"],
        "keywords_rev": ["tuyệt vọng", "mất niềm tin", "tự ti"],
        "upright": "Sau những bóng tối, ánh sao dẫn lối. Hãy giữ vững niềm tin và hy vọng — vũ trụ đang chữa lành bạn và những điều tốt đẹp đang trên đường đến.",
        "reversed": "Nỗi tuyệt vọng và mất niềm tin đang bao trùm bạn. Hãy tìm lại nguồn cảm hứng và nhớ rằng bóng tối không kéo dài mãi mãi.",
    },
    {
        "id": 18,
        "name": "Mặt Trăng",
        "english": "The Moon",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_18_Moon.jpg"),
        "keywords_up": ["ảo tưởng", "lo âu", "tiềm thức", "bí ẩn"],
        "keywords_rev": ["sợ hãi được giải tỏa", "sự thật hiện ra", "nhầm lẫn qua đi"],
        "upright": "Mọi thứ không như vẻ bề ngoài. Nỗi sợ hãi và ảo giác từ tiềm thức đang ảnh hưởng đến bạn. Hãy tin vào trực giác nhưng cũng cần kiểm chứng thực tế.",
        "reversed": "Sương mù đang tan dần, sự thật bắt đầu lộ diện. Nỗi lo âu và ảo tưởng đang giảm bớt — bạn có thể nhìn thấy rõ hơn bây giờ.",
    },
    {
        "id": 19,
        "name": "Mặt Trời",
        "english": "The Sun",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_19_Sun.jpg"),
        "keywords_up": ["niềm vui", "thành công", "sinh lực", "sự rõ ràng"],
        "keywords_rev": ["niềm vui bị che khuất", "lạc quan quá mức", "thất bại tạm thời"],
        "upright": "Ánh sáng và niềm vui tràn ngập! Đây là lá bài hạnh phúc nhất trong bộ bài. Thành công, sức khỏe và sự rõ ràng đang chờ bạn — tận hưởng giai đoạn tươi sáng này.",
        "reversed": "Ánh sáng đang bị che khuất tạm thời. Đừng từ bỏ — niềm vui và thành công vẫn có thể đạt được, chỉ cần một chút kiên nhẫn hơn.",
    },
    {
        "id": 20,
        "name": "Sự Phán Xét",
        "english": "Judgement",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_20_Judgement.jpg"),
        "keywords_up": ["thức tỉnh", "tha thứ", "tái sinh", "lời kêu gọi"],
        "keywords_rev": ["tự chỉ trích", "nghi ngờ bản thân", "bỏ lỡ lời kêu gọi"],
        "upright": "Một sự thức tỉnh sâu sắc đang diễn ra. Đây là lúc tha thứ cho bản thân và người khác, rũ bỏ quá khứ và đáp lại tiếng gọi của số phận với trái tim rộng mở.",
        "reversed": "Bạn đang quá khắt khe với bản thân hoặc không dám đáp lại lời kêu gọi của cuộc sống. Hãy buông bỏ sự phán xét và chấp nhận cơ hội thay đổi.",
    },
    {
        "id": 21,
        "name": "Thế Giới",
        "english": "The World",
        "arcana": "major",
        "suit": None,
        "image": img("RWS_Tarot_21_World.jpg"),
        "keywords_up": ["hoàn thành", "thành tựu", "tích hợp", "toàn vẹn"],
        "keywords_rev": ["dang dở", "thiếu kết thúc", "trì hoãn thành công"],
        "upright": "Bạn đang ở đỉnh cao của một chu kỳ hoàn chỉnh. Mọi nỗ lực đã được đền đáp xứng đáng. Hãy ăn mừng thành tựu và sẵn sàng cho chu kỳ tiếp theo.",
        "reversed": "Hành trình chưa hoàn thành — còn vài bước cuối cần thực hiện. Đừng bỏ cuộc lúc gần đến đích, hãy kiên trì thêm một chút nữa.",
    },

    # ══════════════════════════════════════════
    # MINOR ARCANA — GẬY (WANDS) — Lửa, đam mê, hành động
    # ══════════════════════════════════════════
    {
        "id": 22,
        "name": "Át Gậy",
        "english": "Ace of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands01.jpg"),
        "keywords_up": ["cảm hứng mới", "đam mê", "tiềm năng", "sáng tạo"],
        "keywords_rev": ["trì hoãn", "thiếu động lực", "cơ hội bị bỏ lỡ"],
        "upright": "Ngọn lửa đam mê vừa được thắp sáng! Một cơ hội sáng tạo hoặc dự án mới đầy hứa hẹn đang mở ra. Hãy nắm bắt nguồn năng lượng này và bắt đầu ngay.",
        "reversed": "Cảm hứng bị chặn lại. Bạn đang thấy thiếu động lực hoặc một dự án bị đình trệ. Tìm lại ngọn lửa nội tâm của mình.",
    },
    {
        "id": 23,
        "name": "Hai Gậy",
        "english": "Two of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands02.jpg"),
        "keywords_up": ["lập kế hoạch", "tầm nhìn xa", "lựa chọn tương lai", "can đảm"],
        "keywords_rev": ["thiếu kế hoạch", "sợ hãi trước thay đổi", "tự giới hạn"],
        "upright": "Bạn đang đứng trước một ngã rẽ quan trọng. Hãy nhìn xa hơn, lập kế hoạch táo bạo và dũng cảm bước ra khỏi vùng an toàn.",
        "reversed": "Nỗi sợ hãi đang ngăn bạn tiến lên. Hãy tin tưởng vào kế hoạch của mình và không để sự do dự kéo bạn lại.",
    },
    {
        "id": 24,
        "name": "Ba Gậy",
        "english": "Three of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands03.jpg"),
        "keywords_up": ["mở rộng", "nhìn xa trông rộng", "chờ đợi kết quả"],
        "keywords_rev": ["chậm trễ", "thiếu kiên nhẫn", "trở ngại bất ngờ"],
        "upright": "Những gì bạn gieo trồng đang bắt đầu nảy mầm. Hãy kiên nhẫn chờ đợi kết quả và chuẩn bị mở rộng tầm với ra xa hơn nữa.",
        "reversed": "Kết quả bị trì hoãn gây thất vọng. Hãy xem xét lại kế hoạch và tìm cách vượt qua những rào cản đang xuất hiện.",
    },
    {
        "id": 25,
        "name": "Bốn Gậy",
        "english": "Four of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands04.jpg"),
        "keywords_up": ["ăn mừng", "hài hòa", "ổn định", "cột mốc"],
        "keywords_rev": ["bất ổn trong gia đình", "thiếu nền tảng", "vui mừng bị hoãn"],
        "upright": "Đây là thời điểm để ăn mừng thành tựu và tận hưởng sự hài hòa. Một cột mốc quan trọng đã đạt được — hãy cùng chia sẻ niềm vui này với những người thân yêu.",
        "reversed": "Bất hòa trong gia đình hoặc môi trường sống thiếu ổn định. Cần tập trung xây dựng lại nền tảng vững chắc hơn.",
    },
    {
        "id": 26,
        "name": "Năm Gậy",
        "english": "Five of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands05.jpg"),
        "keywords_up": ["xung đột", "cạnh tranh", "bất đồng", "thử thách"],
        "keywords_rev": ["tránh xung đột", "giải quyết tranh chấp", "hòa giải"],
        "upright": "Môi trường đang đầy cạnh tranh và xung đột. Đây không hẳn là điều xấu — sự va chạm này có thể làm bạn mạnh mẽ hơn nếu bạn giữ được bình tĩnh.",
        "reversed": "Bạn đang né tránh xung đột cần thiết, hoặc ngược lại, các tranh chấp đang được giải quyết. Tìm cách đối thoại thẳng thắn hơn.",
    },
    {
        "id": 27,
        "name": "Sáu Gậy",
        "english": "Six of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands06.jpg"),
        "keywords_up": ["chiến thắng", "công nhận", "thành công công khai", "tự tin"],
        "keywords_rev": ["tự cao", "thành công riêng tư", "thiếu công nhận"],
        "upright": "Chiến thắng và sự công nhận đang đến với bạn. Hãy tự tin bước ra ánh sáng và đón nhận những lời khen ngợi xứng đáng cho nỗ lực của mình.",
        "reversed": "Thành công nhưng thiếu sự công nhận, hoặc bạn đang quá tự cao. Hãy khiêm tốn và tiếp tục làm việc chăm chỉ.",
    },
    {
        "id": 28,
        "name": "Bảy Gậy",
        "english": "Seven of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands07.jpg"),
        "keywords_up": ["bảo vệ lập trường", "dũng cảm", "kiên trì", "thách thức"],
        "keywords_rev": ["bỏ cuộc", "cảm thấy áp lực quá lớn", "không nhất quán"],
        "upright": "Bạn đang bị thách thức nhưng đứng ở vị trí cao hơn. Hãy bảo vệ lập trường và niềm tin của mình — bạn có đủ sức mạnh để vượt qua.",
        "reversed": "Áp lực quá lớn khiến bạn muốn bỏ cuộc. Hãy đánh giá lại xem điều gì thực sự xứng đáng để chiến đấu.",
    },
    {
        "id": 29,
        "name": "Tám Gậy",
        "english": "Eight of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands08.jpg"),
        "keywords_up": ["hành động nhanh", "tin tức đến", "tiến độ", "di chuyển"],
        "keywords_rev": ["chậm trễ", "tin tức xấu", "thiếu định hướng"],
        "upright": "Mọi thứ đang diễn ra với tốc độ cao! Tin tức quan trọng sắp đến, hành động nhanh chóng và chuẩn bị cho những thay đổi chóng mặt.",
        "reversed": "Sự chậm trễ và gián đoạn đang xảy ra. Hãy kiên nhẫn và đừng ép buộc mọi thứ diễn ra theo ý mình.",
    },
    {
        "id": 30,
        "name": "Chín Gậy",
        "english": "Nine of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands09.jpg"),
        "keywords_up": ["kiên trì", "mệt mỏi nhưng tiếp tục", "phòng thủ", "gần đến đích"],
        "keywords_rev": ["kiệt sức", "bỏ cuộc trước đích", "cứng nhắc"],
        "upright": "Bạn đã mệt mỏi nhưng đang gần đến đích. Hãy tiếp tục thêm một bước nữa — sức bền của bạn sẽ được đền đáp xứng đáng.",
        "reversed": "Kiệt sức toàn diện. Đây là lúc cần nghỉ ngơi và phục hồi sức lực thay vì cố sức tiếp tục.",
    },
    {
        "id": 31,
        "name": "Mười Gậy",
        "english": "Ten of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands10.jpg"),
        "keywords_up": ["gánh nặng", "trách nhiệm quá lớn", "áp lực", "hoàn thành"],
        "keywords_rev": ["buông bỏ gánh nặng", "uỷ quyền", "giải phóng"],
        "upright": "Bạn đang mang quá nhiều gánh nặng trên vai. Hãy học cách phân chia trách nhiệm và đặt ra giới hạn — bạn không cần làm tất cả một mình.",
        "reversed": "Đã đến lúc buông bỏ những gánh nặng không còn cần thiết. Hãy uỷ quyền và tin tưởng người khác có thể giúp đỡ.",
    },
    {
        "id": 32,
        "name": "Thị Vệ Gậy",
        "english": "Page of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands11.jpg"),
        "keywords_up": ["nhiệt huyết", "khám phá", "tin tức tốt", "đam mê mới"],
        "keywords_rev": ["thiếu định hướng", "năng lượng lãng phí", "xốc nổi"],
        "upright": "Năng lượng trẻ trung và nhiệt huyết đang tràn đầy. Đây là lúc khám phá, thử nghiệm và đón nhận những ý tưởng mới mẻ.",
        "reversed": "Năng lượng đang bị phân tán hoặc hướng sai. Cần tập trung hơn vào một mục tiêu cụ thể.",
    },
    {
        "id": 33,
        "name": "Kỵ Sĩ Gậy",
        "english": "Knight of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands12.jpg"),
        "keywords_up": ["hành động táo bạo", "phiêu lưu", "tự tin", "nhanh nhẹn"],
        "keywords_rev": ["bốc đồng", "thiếu kiên nhẫn", "hung hăng"],
        "upright": "Thời điểm hành động mạnh mẽ và táo bạo. Hãy tin vào bản năng và tiến lên phía trước với đầy tự tin và nhiệt huyết.",
        "reversed": "Sự bốc đồng và thiếu kiên nhẫn đang gây ra vấn đề. Hãy dừng lại một chút và suy nghĩ trước khi lao vào.",
    },
    {
        "id": 34,
        "name": "Hoàng Hậu Gậy",
        "english": "Queen of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands13.jpg"),
        "keywords_up": ["tự tin", "lôi cuốn", "nhiệt huyết", "sáng tạo mạnh mẽ"],
        "keywords_rev": ["ích kỷ", "ganh ghét", "thiếu tập trung"],
        "upright": "Sức hút và sự tự tin tỏa sáng. Bạn đang ở đỉnh cao năng lực sáng tạo — hãy dẫn dắt, truyền cảm hứng và không ngại thể hiện bản thân.",
        "reversed": "Ganh tị hoặc thiếu tập trung đang cản trở. Hãy quay lại với giá trị cốt lõi và động lực thật sự của mình.",
    },
    {
        "id": 35,
        "name": "Vua Gậy",
        "english": "King of Wands",
        "arcana": "minor",
        "suit": "Gậy",
        "image": img("RWS_Tarot_Wands14.jpg"),
        "keywords_up": ["lãnh đạo", "tầm nhìn", "quyết đoán", "truyền cảm hứng"],
        "keywords_rev": ["độc đoán", "bốc đồng", "lạm dụng quyền lực"],
        "upright": "Lãnh đạo bằng tầm nhìn và đam mê. Bạn có khả năng truyền cảm hứng cho người khác và dẫn dắt cả đội nhóm đến thành công.",
        "reversed": "Lạm dụng quyền lực hoặc phong cách lãnh đạo độc đoán đang gây tổn hại. Cần lắng nghe người khác nhiều hơn.",
    },

    # ══════════════════════════════════════════
    # MINOR ARCANA — CHÉN (CUPS) — Nước, cảm xúc, trực giác
    # ══════════════════════════════════════════
    {
        "id": 36,
        "name": "Át Chén",
        "english": "Ace of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups01.jpg"),
        "keywords_up": ["tình yêu mới", "cảm xúc tràn đầy", "trực giác", "chữa lành"],
        "keywords_rev": ["cảm xúc bị kìm nén", "tình yêu bị từ chối", "tự thương"],
        "upright": "Trái tim đang mở ra với tình yêu và cảm xúc dào dạt. Một mối quan hệ mới hoặc sự kết nối cảm xúc sâu sắc đang bắt đầu hé nở.",
        "reversed": "Cảm xúc đang bị kìm nén hoặc bạn sợ mở lòng. Hãy chữa lành những vết thương cũ trước khi tiếp tục.",
    },
    {
        "id": 37,
        "name": "Hai Chén",
        "english": "Two of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups02.jpg"),
        "keywords_up": ["kết nối", "tình yêu đôi lứa", "đối tác", "hài hòa"],
        "keywords_rev": ["bất hòa", "mất cân bằng trong quan hệ", "chia tay"],
        "upright": "Một mối kết nối đẹp đẽ đang nảy sinh — có thể là tình yêu, tình bạn hay quan hệ đối tác. Sự tương hỗ và hiểu biết lẫn nhau đang được xây dựng.",
        "reversed": "Sự mất cân bằng hoặc bất hòa trong mối quan hệ. Cần đối thoại thành thật để tìm lại sự hài hòa.",
    },
    {
        "id": 38,
        "name": "Ba Chén",
        "english": "Three of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups03.jpg"),
        "keywords_up": ["ăn mừng", "tình bạn", "cộng đồng", "niềm vui chung"],
        "keywords_rev": ["cô lập", "thái quá trong tiệc tùng", "thất vọng với bạn bè"],
        "upright": "Niềm vui và sự kết nối cộng đồng. Đây là thời điểm tụ họp, ăn mừng và trân trọng những tình bạn quý giá trong cuộc đời bạn.",
        "reversed": "Cô đơn hoặc thất vọng với bạn bè. Cần đánh giá lại các mối quan hệ xem ai thực sự ở đó vì bạn.",
    },
    {
        "id": 39,
        "name": "Bốn Chén",
        "english": "Four of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups04.jpg"),
        "keywords_up": ["suy tư", "thờ ơ", "nhìn vào nội tâm", "bỏ lỡ cơ hội"],
        "keywords_rev": ["thoát ra khỏi suy tư", "chấp nhận cơ hội mới", "thức tỉnh"],
        "upright": "Bạn đang chìm đắm trong suy nghĩ và bỏ qua những điều tốt đẹp xung quanh. Hãy ngẩng đầu lên và nhìn xem vũ trụ đang dâng tặng bạn điều gì.",
        "reversed": "Bạn đang thoát ra khỏi trạng thái thờ ơ và sẵn sàng đón nhận cơ hội mới. Tinh thần đang hồi sinh.",
    },
    {
        "id": 40,
        "name": "Năm Chén",
        "english": "Five of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups05.jpg"),
        "keywords_up": ["mất mát", "đau buồn", "hối tiếc", "thất vọng"],
        "keywords_rev": ["tha thứ", "chuyển sang phía trước", "chấp nhận mất mát"],
        "upright": "Nỗi đau và sự mất mát đang hiện diện. Hãy để bản thân đau buồn đúng mức, nhưng đừng quên nhìn về phía sau — vẫn còn những điều quý giá chưa mất.",
        "reversed": "Bạn đang bắt đầu chữa lành và tha thứ. Dần dần bước ra khỏi bóng tối của quá khứ để hướng đến tương lai.",
    },
    {
        "id": 41,
        "name": "Sáu Chén",
        "english": "Six of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups06.jpg"),
        "keywords_up": ["hoài niệm", "ký ức tuổi thơ", "đơn giản", "cho đi"],
        "keywords_rev": ["sống trong quá khứ", "lý tưởng hóa", "cần trưởng thành"],
        "upright": "Ký ức ngọt ngào và sự hoài niệm đang ghé thăm. Có thể người cũ hoặc nơi cũ sẽ xuất hiện. Hãy trân trọng sự đơn giản và thuần khiết của quá khứ.",
        "reversed": "Bạn đang bị mắc kẹt trong ký ức và lý tưởng hóa quá khứ. Đã đến lúc trưởng thành hơn và tập trung vào hiện tại.",
    },
    {
        "id": 42,
        "name": "Bảy Chén",
        "english": "Seven of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups07.jpg"),
        "keywords_up": ["ảo tưởng", "quá nhiều lựa chọn", "mơ mộng", "ảo vọng"],
        "keywords_rev": ["rõ ràng hơn", "tập trung", "thực tế"],
        "upright": "Quá nhiều lựa chọn đang gây ra sự mơ hồ. Cẩn thận với những ảo tưởng và lời hứa hào nhoáng — không phải mọi giấc mơ đều thực chất.",
        "reversed": "Bạn đang trở nên thực tế và tập trung hơn. Sương mù đang tan và bạn thấy rõ con đường phía trước.",
    },
    {
        "id": 43,
        "name": "Tám Chén",
        "english": "Eight of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups08.jpg"),
        "keywords_up": ["rời bỏ", "tìm kiếm sâu hơn", "chuyển hướng", "dũng cảm ra đi"],
        "keywords_rev": ["sợ ra đi", "ở lại dù không hạnh phúc", "hy vọng mong manh"],
        "upright": "Dù đau đớn, bạn cần bỏ lại những điều đã quen thuộc để tìm kiếm điều gì đó có ý nghĩa hơn. Cuộc hành trình tâm linh đang gọi bạn.",
        "reversed": "Bạn đang do dự giữa rời đi hay ở lại. Hãy lắng nghe trái tim — đôi khi ở lại cũng cần dũng cảm như ra đi.",
    },
    {
        "id": 44,
        "name": "Chín Chén",
        "english": "Nine of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups09.jpg"),
        "keywords_up": ["mãn nguyện", "điều ước thành sự thật", "hạnh phúc", "sung mãn"],
        "keywords_rev": ["không thỏa mãn", "vật chất không đủ", "điều ước sai lầm"],
        "upright": "Lá bài may mắn! Điều ước của bạn có cơ hội thành sự thật. Hãy biết ơn và tận hưởng sự mãn nguyện đang đến.",
        "reversed": "Dù có đủ nhưng vẫn cảm thấy thiếu thốn. Hãy nhìn lại những gì bạn thực sự cần, không chỉ là những gì bạn muốn.",
    },
    {
        "id": 45,
        "name": "Mười Chén",
        "english": "Ten of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups10.jpg"),
        "keywords_up": ["hạnh phúc gia đình", "hài hòa lâu dài", "tình yêu trọn vẹn"],
        "keywords_rev": ["bất hòa gia đình", "hạnh phúc vỡ vụn", "kỳ vọng không thực tế"],
        "upright": "Hạnh phúc viên mãn và hài hòa trong gia đình. Đây là biểu tượng của tình yêu trọn vẹn và cuộc sống đủ đầy cả vật chất lẫn tinh thần.",
        "reversed": "Bất hòa trong gia đình hoặc kỳ vọng không thực tế về hạnh phúc. Cần xây dựng lại nền tảng cảm xúc vững chắc hơn.",
    },
    {
        "id": 46,
        "name": "Thị Vệ Chén",
        "english": "Page of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups11.jpg"),
        "keywords_up": ["nhạy cảm", "trực giác mở", "tin tức tình cảm", "sáng tạo"],
        "keywords_rev": ["cảm xúc không trưởng thành", "dễ bị tổn thương quá mức"],
        "upright": "Tin nhắn xúc động hoặc cảm hứng sáng tạo đang đến. Hãy mở lòng với những điều mới mẻ và tin tưởng vào trực giác nhạy bén của mình.",
        "reversed": "Cảm xúc thiếu trưởng thành hoặc quá nhạy cảm gây ra vấn đề. Cần học cách xử lý cảm xúc một cách lành mạnh hơn.",
    },
    {
        "id": 47,
        "name": "Kỵ Sĩ Chén",
        "english": "Knight of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups12.jpg"),
        "keywords_up": ["lãng mạn", "đề nghị", "theo đuổi giấc mơ", "quyến rũ"],
        "keywords_rev": ["thao túng cảm xúc", "không thực tế", "thất thường"],
        "upright": "Lời đề nghị lãng mạn hoặc cơ hội theo đuổi điều bạn đam mê đang đến. Hãy đón nhận với trái tim rộng mở nhưng đầu óc tỉnh táo.",
        "reversed": "Sự thất thường về cảm xúc hoặc ai đó đang thao túng bạn. Hãy cẩn thận với những lời hứa hoa mỹ thiếu thực chất.",
    },
    {
        "id": 48,
        "name": "Hoàng Hậu Chén",
        "english": "Queen of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups13.jpg"),
        "keywords_up": ["đồng cảm", "trực giác sâu sắc", "nuôi dưỡng cảm xúc", "chữa lành"],
        "keywords_rev": ["cảm xúc lệ thuộc", "dễ bị ảnh hưởng", "mất cân bằng"],
        "upright": "Sự đồng cảm và trực giác đang dẫn đường. Hãy tin vào khả năng chữa lành và nuôi dưỡng của bạn — cả với bản thân lẫn người khác.",
        "reversed": "Cảm xúc đang lấn át lý trí. Hãy chú ý đến ranh giới cảm xúc và không để người khác lợi dụng lòng tốt của bạn.",
    },
    {
        "id": 49,
        "name": "Vua Chén",
        "english": "King of Cups",
        "arcana": "minor",
        "suit": "Chén",
        "image": img("RWS_Tarot_Cups14.jpg"),
        "keywords_up": ["cân bằng cảm xúc", "trí tuệ cảm xúc", "từ bi", "kiên nhẫn"],
        "keywords_rev": ["thao túng cảm xúc", "lạnh lùng", "không ổn định"],
        "upright": "Sự chín chắn về cảm xúc và khả năng lãnh đạo bằng trái tim. Hãy điều khiển cảm xúc một cách khôn ngoan và đưa ra quyết định bằng cả lý trí lẫn tình cảm.",
        "reversed": "Cảm xúc bị kìm nén hoặc thao túng người khác. Cần tìm lại sự cân bằng giữa lý trí và trái tim.",
    },

    # ══════════════════════════════════════════
    # MINOR ARCANA — KIẾM (SWORDS) — Không khí, trí tuệ, sự thật
    # ══════════════════════════════════════════
    {
        "id": 50,
        "name": "Át Kiếm",
        "english": "Ace of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords01.jpg"),
        "keywords_up": ["sự thật sắc bén", "rõ ràng", "đột phá", "công lý"],
        "keywords_rev": ["hỗn loạn tư duy", "nói dối", "lạm dụng quyền lực"],
        "upright": "Sự thật sắc nét đang cắt xuyên qua mọi mơ hồ. Đây là lúc tư duy rõ ràng, quyết định dứt khoát và nói ra sự thật dù có đau đớn.",
        "reversed": "Tư duy lộn xộn hoặc sự dối trá đang gây rối. Hãy tìm lại sự rõ ràng và đừng để người khác thao túng nhận thức của bạn.",
    },
    {
        "id": 51,
        "name": "Hai Kiếm",
        "english": "Two of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords02.jpg"),
        "keywords_up": ["bế tắc", "khó quyết định", "tránh né", "cân bằng"],
        "keywords_rev": ["thông tin hé lộ", "quyết định bắt buộc", "bế tắc kết thúc"],
        "upright": "Bạn đang đứng trước một quyết định khó khăn và đang né tránh nó. Hãy dũng cảm nhìn thẳng vào thực tế — việc tiếp tục trốn tránh sẽ chỉ khiến mọi thứ tệ hơn.",
        "reversed": "Sự bế tắc đang dần được tháo gỡ, thông tin mới sắp xuất hiện. Đây là lúc đưa ra quyết định cuối cùng.",
    },
    {
        "id": 52,
        "name": "Ba Kiếm",
        "english": "Three of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords03.jpg"),
        "keywords_up": ["đau lòng", "phản bội", "nỗi buồn", "mất mát"],
        "keywords_rev": ["chữa lành", "tha thứ", "vượt qua đau đớn"],
        "upright": "Nỗi đau của sự phản bội hoặc mất mát đang hiện diện. Hãy để bản thân đau — đây là bước cần thiết để chữa lành. Cơn bão này rồi sẽ qua.",
        "reversed": "Quá trình chữa lành đang diễn ra. Dần dần bạn đang vượt qua nỗi đau và tìm lại bình yên.",
    },
    {
        "id": 53,
        "name": "Bốn Kiếm",
        "english": "Four of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords04.jpg"),
        "keywords_up": ["nghỉ ngơi", "phục hồi", "thiền định", "tạm dừng"],
        "keywords_rev": ["trở lại hành động", "kiệt sức", "không chịu nghỉ ngơi"],
        "upright": "Cơ thể và tâm trí cần được nghỉ ngơi. Đây là lúc rút lui, thiền định và nạp lại năng lượng trước khi tiếp tục cuộc chiến.",
        "reversed": "Sau giai đoạn nghỉ ngơi, đã đến lúc trở lại hành động. Hoặc bạn đang không chịu nghỉ ngơi dù cơ thể đang cần.",
    },
    {
        "id": 54,
        "name": "Năm Kiếm",
        "english": "Five of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords05.jpg"),
        "keywords_up": ["chiến thắng rỗng tuếch", "xung đột", "tự cao", "thua lỗ"],
        "keywords_rev": ["hậu quả của xung đột", "hòa giải", "nhìn nhận sai lầm"],
        "upright": "Chiến thắng nhưng không ai được lợi. Cuộc xung đột này để lại hậu quả — hãy cân nhắc có đáng hay không khi chiến đấu đến cùng.",
        "reversed": "Hậu quả của xung đột đang đổ về. Đây là lúc hòa giải và học từ những sai lầm đã qua.",
    },
    {
        "id": 55,
        "name": "Sáu Kiếm",
        "english": "Six of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords06.jpg"),
        "keywords_up": ["chuyển tiếp", "rời xa rắc rối", "bình yên đang đến", "hành trình"],
        "keywords_rev": ["kháng cự thay đổi", "hành lý nặng nề quá khứ"],
        "upright": "Bạn đang rời xa vùng biển dông bão tiến về bờ bình yên. Quá trình chuyển tiếp này không dễ dàng nhưng cần thiết và đúng hướng.",
        "reversed": "Bạn đang mang theo quá nhiều hành lý từ quá khứ. Hãy buông bỏ những gì không cần thiết để hành trình nhẹ nhàng hơn.",
    },
    {
        "id": 56,
        "name": "Bảy Kiếm",
        "english": "Seven of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords07.jpg"),
        "keywords_up": ["lừa lọc", "chiến lược", "hành động một mình", "né tránh"],
        "keywords_rev": ["bị phát hiện", "trở lại lương tâm", "thú nhận"],
        "upright": "Ai đó đang không trung thực hoặc bạn đang phải dùng chiến lược khéo léo. Hãy cẩn thận với sự lừa dối — có thể từ người khác hoặc chính mình.",
        "reversed": "Sự dối trá sắp bị phơi bày hoặc lương tâm đang thức tỉnh. Đây là cơ hội để trở về với sự trung thực.",
    },
    {
        "id": 57,
        "name": "Tám Kiếm",
        "english": "Eight of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords08.jpg"),
        "keywords_up": ["bị giam cầm", "tự giới hạn", "nạn nhân", "sợ hãi"],
        "keywords_rev": ["tự giải phóng", "nhìn thấy lối ra", "thức tỉnh"],
        "upright": "Bạn đang cảm thấy bị mắc kẹt — nhưng thực ra xiềng xích ấy phần lớn do bạn tự tạo ra. Hãy cởi bỏ băng mắt và nhìn thấy rằng lối ra luôn tồn tại.",
        "reversed": "Bạn bắt đầu nhìn thấy những giới hạn tự đặt ra và dần thoát khỏi chúng. Sự tự do đang gần kề.",
    },
    {
        "id": 58,
        "name": "Chín Kiếm",
        "english": "Nine of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords09.jpg"),
        "keywords_up": ["lo âu", "ác mộng", "tội lỗi", "tư duy tiêu cực"],
        "keywords_rev": ["vượt qua lo âu", "chấp nhận sự thật", "hy vọng trở lại"],
        "upright": "Những lo âu và nỗi sợ ban đêm đang ám ảnh bạn. Hãy nhớ: tâm trí thường phóng đại nỗi sợ. Tìm người đáng tin để chia sẻ — bạn không phải một mình.",
        "reversed": "Bạn đang dần vượt qua giai đoạn tối tăm nhất. Ánh sáng đang bắt đầu ló dạng phía cuối đường hầm.",
    },
    {
        "id": 59,
        "name": "Mười Kiếm",
        "english": "Ten of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords10.jpg"),
        "keywords_up": ["kết thúc đau đớn", "phản bội", "chạm đáy", "bước ngoặt"],
        "keywords_rev": ["hồi phục", "sống sót", "bài học đã học"],
        "upright": "Đây là điểm chạm đáy — không thể xuống thấp hơn nữa. Nhưng đây cũng là bình minh mới: khi mặt trời mọc, một trang mới bắt đầu.",
        "reversed": "Bạn đang hồi phục từ giai đoạn khó khăn nhất. Sức mạnh đang trở lại — hãy tiến về phía trước với trí tuệ mới.",
    },
    {
        "id": 60,
        "name": "Thị Vệ Kiếm",
        "english": "Page of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords11.jpg"),
        "keywords_up": ["tò mò", "nhanh trí", "tin tức", "học hỏi"],
        "keywords_rev": ["tin đồn", "hành động thiếu suy nghĩ", "sự tàn nhẫn"],
        "upright": "Trí tuệ sắc bén và sự tò mò đang dẫn đường. Đây là lúc học hỏi, đặt câu hỏi và sẵn sàng đối mặt với sự thật.",
        "reversed": "Tin đồn hoặc hành động bốc đồng đang gây rắc rối. Hãy suy nghĩ trước khi nói và kiểm chứng thông tin trước khi tin.",
    },
    {
        "id": 61,
        "name": "Kỵ Sĩ Kiếm",
        "english": "Knight of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords12.jpg"),
        "keywords_up": ["hành động nhanh", "quyết đoán", "tham vọng", "trực tiếp"],
        "keywords_rev": ["liều lĩnh", "hung hăng", "thiếu kế hoạch"],
        "upright": "Hành động với tốc độ và quyết tâm. Đây là lúc tiến lên phía trước mạnh mẽ — nhưng hãy đảm bảo bạn đang chạy đúng hướng.",
        "reversed": "Sự liều lĩnh và thiếu kế hoạch đang gây ra vấn đề. Hãy làm chậm lại và suy nghĩ kỹ trước khi hành động.",
    },
    {
        "id": 62,
        "name": "Hoàng Hậu Kiếm",
        "english": "Queen of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords13.jpg"),
        "keywords_up": ["trực tiếp", "độc lập", "sắc bén", "trải đời"],
        "keywords_rev": ["lạnh lùng", "cay nghiệt", "cô đơn do tự chọn"],
        "upright": "Sự rõ ràng và quyết đoán là sức mạnh của bạn. Không cần phép xã giao thừa thãi — hãy nói thẳng, hành động quyết liệt và giữ vững ranh giới.",
        "reversed": "Sự cay nghiệt và lạnh lùng đang xây rào cản giữa bạn và người khác. Hãy để lộ một chút mềm mại trong lớp giáp của mình.",
    },
    {
        "id": 63,
        "name": "Vua Kiếm",
        "english": "King of Swords",
        "arcana": "minor",
        "suit": "Kiếm",
        "image": img("RWS_Tarot_Swords14.jpg"),
        "keywords_up": ["quyền uy trí tuệ", "công bằng", "sự thật khắt khe", "phán xét"],
        "keywords_rev": ["độc đoán", "thao túng", "lạm dụng tri thức"],
        "upright": "Lãnh đạo bằng lý trí và công lý. Bạn có khả năng phân tích sắc bén và đưa ra quyết định công bằng dựa trên sự thật.",
        "reversed": "Lạm dụng quyền lực trí tuệ hoặc thiên vị trong phán xét. Hãy đảm bảo quyết định của bạn thực sự xuất phát từ lý trí, không phải từ ego.",
    },

    # ══════════════════════════════════════════
    # MINOR ARCANA — XU (PENTACLES) — Đất, vật chất, thực tế
    # ══════════════════════════════════════════
    {
        "id": 64,
        "name": "Át Xu",
        "english": "Ace of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents01.jpg"),
        "keywords_up": ["cơ hội tài chính", "thịnh vượng", "nền tảng mới", "an toàn"],
        "keywords_rev": ["bỏ lỡ cơ hội", "thiếu kế hoạch tài chính", "bất ổn"],
        "upright": "Hạt giống thịnh vượng đang được gieo trồng. Một cơ hội tài chính hoặc vật chất mới đang xuất hiện — hãy nắm bắt và nuôi dưỡng nó cẩn thận.",
        "reversed": "Cơ hội tốt đang bị bỏ lỡ do thiếu chuẩn bị. Hãy xem lại kế hoạch tài chính và đưa ra nền tảng vững chắc hơn.",
    },
    {
        "id": 65,
        "name": "Hai Xu",
        "english": "Two of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents02.jpg"),
        "keywords_up": ["cân bằng nhiều việc", "thích nghi", "linh hoạt", "quản lý"],
        "keywords_rev": ["mất cân bằng", "quá tải", "quản lý kém"],
        "upright": "Bạn đang juggling nhiều trách nhiệm cùng lúc. Cần linh hoạt và khéo léo trong việc phân bổ thời gian và nguồn lực.",
        "reversed": "Bạn đang bị quá tải và mất cân bằng. Hãy ưu tiên và bỏ bớt những gì không cần thiết.",
    },
    {
        "id": 66,
        "name": "Ba Xu",
        "english": "Three of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents03.jpg"),
        "keywords_up": ["hợp tác", "kỹ năng", "học nghề", "làm việc nhóm"],
        "keywords_rev": ["thiếu hợp tác", "kỹ năng kém", "làm việc riêng lẻ"],
        "upright": "Thành công đến từ sự hợp tác và phát triển kỹ năng. Hãy làm việc cùng người khác và liên tục học hỏi để nâng cao tay nghề.",
        "reversed": "Thiếu phối hợp trong nhóm hoặc kỹ năng chưa đủ để hoàn thành nhiệm vụ. Cần đầu tư hơn vào học hỏi và giao tiếp.",
    },
    {
        "id": 67,
        "name": "Bốn Xu",
        "english": "Four of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents04.jpg"),
        "keywords_up": ["tiết kiệm", "kiểm soát tài chính", "bảo thủ", "an toàn"],
        "keywords_rev": ["keo kiệt", "sợ mất mát", "bám víu vật chất"],
        "upright": "Sự thận trọng về tài chính là đúng đắn ở thời điểm này. Nhưng hãy cẩn thận không để nỗi sợ mất mát cản trở cơ hội phát triển.",
        "reversed": "Sự keo kiệt hoặc bám víu vật chất quá mức đang cản trở dòng chảy phong phú. Hãy học cách buông bỏ để nhận nhiều hơn.",
    },
    {
        "id": 68,
        "name": "Năm Xu",
        "english": "Five of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents05.jpg"),
        "keywords_up": ["khó khăn tài chính", "bất an", "bị bỏ lại", "thiếu thốn"],
        "keywords_rev": ["hồi phục", "được giúp đỡ", "vượt qua khó khăn"],
        "upright": "Giai đoạn khó khăn về tài chính hoặc cảm giác bị bỏ rơi đang ảnh hưởng. Hãy tìm kiếm sự giúp đỡ — cánh cửa luôn mở dù bạn chưa nhìn thấy.",
        "reversed": "Khó khăn đang dần qua đi. Sự giúp đỡ đang đến hoặc bạn đang tìm lại được sức mạnh nội tâm.",
    },
    {
        "id": 69,
        "name": "Sáu Xu",
        "english": "Six of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents06.jpg"),
        "keywords_up": ["hào phóng", "cho và nhận", "từ thiện", "công bằng"],
        "keywords_rev": ["cho đi có điều kiện", "nợ nần", "không công bằng"],
        "upright": "Sự hào phóng và chia sẻ đang tạo ra chu kỳ phong phú. Hãy cho đi một cách hào phóng — những gì bạn gửi ra sẽ quay trở lại gấp bội.",
        "reversed": "Sự cho đi thiếu chân thành hoặc mất cân bằng trong tài chính. Hãy xem lại các mối quan hệ tài chính để đảm bảo sự công bằng.",
    },
    {
        "id": 70,
        "name": "Bảy Xu",
        "english": "Seven of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents07.jpg"),
        "keywords_up": ["kiên nhẫn chờ đợi", "đánh giá lại", "đầu tư dài hạn"],
        "keywords_rev": ["thiếu kiên nhẫn", "đầu tư kém hiệu quả", "mất tập trung"],
        "upright": "Bạn đã làm việc chăm chỉ và đang chờ đợi kết quả. Đây là lúc đánh giá lại những gì đang hiệu quả và điều chỉnh chiến lược dài hạn.",
        "reversed": "Nỗ lực chưa mang lại kết quả như mong đợi. Hãy xem lại phương pháp — có thể cần thay đổi cách tiếp cận.",
    },
    {
        "id": 71,
        "name": "Tám Xu",
        "english": "Eight of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents08.jpg"),
        "keywords_up": ["chăm chỉ", "học nghề", "kỹ năng", "cải thiện bản thân"],
        "keywords_rev": ["thiếu tập trung", "cầu toàn tiêu cực", "lặp lại vô nghĩa"],
        "upright": "Đây là lúc đầu tư nghiêm túc vào kỹ năng và sự thành thạo. Sự chăm chỉ và kiên nhẫn mài giũa tay nghề sẽ tạo ra nền tảng vững chắc.",
        "reversed": "Bạn đang thiếu tập trung hoặc bị mắc kẹt trong sự hoàn hảo thiếu thực tế. Hãy cân bằng giữa chất lượng và hiệu quả.",
    },
    {
        "id": 72,
        "name": "Chín Xu",
        "english": "Nine of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents09.jpg"),
        "keywords_up": ["độc lập", "tự túc", "sang trọng", "thành quả cá nhân"],
        "keywords_rev": ["phụ thuộc tài chính", "mất thành quả", "cô đơn trong sung túc"],
        "upright": "Bạn đã xây dựng được sự độc lập và sung túc cho bản thân. Hãy tự hào và tận hưởng thành quả từ nỗ lực của chính mình.",
        "reversed": "Sự phụ thuộc tài chính hoặc sung túc bề ngoài che giấu sự trống rỗng bên trong. Hãy xây dựng thành quả thực sự của riêng bạn.",
    },
    {
        "id": 73,
        "name": "Mười Xu",
        "english": "Ten of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents10.jpg"),
        "keywords_up": ["di sản", "thịnh vượng gia đình", "ổn định lâu dài", "truyền thống"],
        "keywords_rev": ["bất ổn gia đình", "mất di sản", "mâu thuẫn về tài sản"],
        "upright": "Sự thịnh vượng và ổn định lâu dài đang được xây dựng. Đây không chỉ là vật chất mà còn là di sản tinh thần truyền từ thế hệ này sang thế hệ khác.",
        "reversed": "Bất ổn trong gia đình về mặt tài chính hoặc giá trị. Cần đối thoại thẳng thắn về những vấn đề đang âm ỉ.",
    },
    {
        "id": 74,
        "name": "Thị Vệ Xu",
        "english": "Page of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents11.jpg"),
        "keywords_up": ["học hỏi thực tế", "cơ hội mới", "chăm chỉ", "tập trung"],
        "keywords_rev": ["thiếu tiến bộ", "lãng phí cơ hội", "thiếu thực tế"],
        "upright": "Một cơ hội học hỏi và phát triển thực tế đang mở ra. Hãy tiếp cận với sự chăm chỉ và tập trung — nền tảng được xây từ những bước nhỏ.",
        "reversed": "Cơ hội đang bị bỏ lỡ do thiếu sự nghiêm túc. Hãy xác định lại mục tiêu và có kế hoạch thực tế hơn.",
    },
    {
        "id": 75,
        "name": "Kỵ Sĩ Xu",
        "english": "Knight of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents12.jpg"),
        "keywords_up": ["kiên định", "trách nhiệm", "chăm chỉ", "đáng tin cậy"],
        "keywords_rev": ["nhàm chán", "cứng nhắc", "không chịu thay đổi"],
        "upright": "Sự kiên định và trách nhiệm là điểm mạnh lúc này. Tiến chậm nhưng chắc — bạn đang xây dựng điều gì đó bền vững và đáng tin cậy.",
        "reversed": "Sự cứng nhắc và nhàm chán đang cản trở sự phát triển. Đôi khi cần linh hoạt và thử những cách tiếp cận mới.",
    },
    {
        "id": 76,
        "name": "Hoàng Hậu Xu",
        "english": "Queen of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents13.jpg"),
        "keywords_up": ["nuôi dưỡng thực tế", "thịnh vượng", "chăm sóc", "an toàn"],
        "keywords_rev": ["bỏ bê bản thân", "bất an tài chính", "phụ thuộc"],
        "upright": "Sự ấm áp và chăm sóc thực tế đang tỏa sáng. Bạn có khả năng tạo ra môi trường sung túc và an toàn cho bản thân và người thân.",
        "reversed": "Bạn đang bỏ bê việc chăm sóc bản thân hoặc lo lắng quá mức về tài chính. Hãy tìm lại sự cân bằng và tin tưởng vào khả năng của mình.",
    },
    {
        "id": 77,
        "name": "Vua Xu",
        "english": "King of Pentacles",
        "arcana": "minor",
        "suit": "Xu",
        "image": img("RWS_Tarot_Pents14.jpg"),
        "keywords_up": ["thành công vật chất", "doanh nhân", "lãnh đạo thực tế", "đáng tin cậy"],
        "keywords_rev": ["tham lam", "lãng phí", "chú trọng vật chất quá mức"],
        "upright": "Thành công vật chất đến từ sự kiên nhẫn và thực tế. Bạn có khả năng quản lý tài nguyên hiệu quả và tạo ra sự phồn thịnh bền vững.",
        "reversed": "Sự tham lam hoặc tập trung quá nhiều vào vật chất đang gây hại. Hãy nhớ rằng giá trị thực sự của cuộc sống không chỉ đo bằng tiền bạc.",
    },
]

# Card back image (for face-down cards)
CARD_BACK = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Rider-Waite_Tarot_pack.jpg/197px-Rider-Waite_Tarot_pack.jpg"

def get_card_by_id(card_id):
    """Lấy lá bài theo ID"""
    return next((c for c in TAROT_CARDS if c["id"] == card_id), None)

def get_random_spread(n=3):
    """Rút ngẫu nhiên n lá bài, kèm trạng thái xuôi/ngược"""
    import random
    cards = random.sample(TAROT_CARDS, n)
    return [(card, random.random() > 0.75) for card in cards]  # (card, is_reversed)
